server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'app_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'app_logs'
          service: 'user-management'
          env: 'development'
          __path__: /logs/*.log
    pipeline_stages:
      # Try to extract structured logs
      - json:
          expressions:
            level: level
            message: msg
            time: time
      # Add timestamp
      - timestamp:
          source: time
          format: RFC3339Nano
      # Add labels based on extracted fields
      - labels:
          level:
